version: "3"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - ./.env
    volumes:
      - ./app:/app/app
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network



# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    name: my_network
    external: true
