import "./globals.css";
import { CustomHeader } from "@/components/header/header";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"

// export const metadata: Metadata = {
//   title: "EventNexus - Your home for events",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="nl" className="dark text-foreground bg-background">
        <body className="dark text-foreground bg-background">
          <CustomHeader />
            {children}
          <SpeedInsights/>
          <Analytics/>
        </body>
      </html>
  );
}
