import type { Metadata } from "next";
import "./globals.css";
import { CustomHeader } from "@/components/header/header";

export const metadata: Metadata = {
  title: "EventNexus - Your home for events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="nl">
        <body>
          <CustomHeader />
          {children}
        </body>
      </html>
  );
}
